
language: python

jobs:
  include:
    - os: linux
      dist: focal
      python: "3.7"
    - os: linux
      dist: focal
      python: "3.9"

install:
  - "pip install -r requirements.txt"
  - "pip install ."

script:
  - rrspex --help
  - spex --help
