
language: python

jobs:
  include:
    - os: linux
      dist: focal
      python: "3.9"
    - os: linux
      dist: focal
      python: "3.9"
    - os: linux
      dist: focal
      python: "3.10"

install:
  - "chmod +x redrock_venv_setup.sh && ./redrock_venv_setup.sh"
  - ". ./redrock-venv/bin/activate"
  - "pip install -r requirements.txt"
  - "pip install ."

script:
  - rrspex --help
  - spex --help
